// Do not edit manually

export const IMAGES = {
  AGRICULTURAL_TRACTOR_APPLYING_PESTICIDES_SOYBEAN_FARM_38: "/images/agricultural-tractor-applying-pesticides-soybean-farm.jpg",
  AJUSTADA_REFLORESTAMENTO_30: "/images/ajustada reflorestamento.png",
  ALGOD_O_SUSTENT_VEL_CERTIFICA_O_AMBIENTAL_2: "/images/Algodão Sustentável - Certificação Ambiental.png",
  ASIAN_SENIOR_FARMER_WORKING_AGRICULTURAL_GARDEN_CORN_FIELD_SUNSET_AGRICULTURE_39: "/images/asian-senior-farmer-working-agricultural-garden-corn-field-sunset-agriculture.jpg",
  BEAUTIFUL_SUNSET_CASTS_WARM_GLOW_FIELD_SOYBEANS_AS_COMBINE_HARVESTER_WORKS_T_40: "/images/beautiful-sunset-casts-warm-glow-field-soybeans-as-combine-harvester-works-t.jpg",
  BIOCHAR_REGENERATIVE_AGRICULTURE_VISUAL_GUIDE_SUSTAINABLE_ORGANIC_FARMING_33: "/images/biochar-regenerative-agriculture-visual-guide-sustainable-organic-farming.jpg",
  CANA_DE_A_CAR_AMANHECER_DOURADO_34: "/images/Cana-de-Açúcar - Amanhecer Dourado.png",
  CANA_PREMIUM_M_OS_NA_COLHEITA_3: "/images/Cana Premium - Mãos na Colheita.png",
  CATTLE_HERD_SUSTAINABLY_RAISED_NELLORE_CATTLE_SMALL_FARMS_PARAIBA_STATE_BRAZIL_4: "/images/cattle-herd-sustainably-raised-nellore-cattle-small-farms-paraiba-state-brazil.jpg",
  CAUCASIAN_MALE_FARMERS_PLANTING_SEEDLINGS_SUNLIT_FIELD_5: "/images/caucasian-male-farmers-planting-seedlings-sunlit-field.jpg",
  CLOUDY_BLUE_SKY_HAND_HELD_WHITE_COTTONS_COTTON_FIELD_35: "/images/cloudy-blue-sky-hand-held-white-cottons-cotton-field.jpg",
  COLHEITA_MECANIZADA_PODER_E_MOVIMENTO_6: "/images/Colheita Mecanizada - Poder e Movimento.png",
  CORN_FIELD_WITH_SILO_BACKGROUND_SILO_BACKGROUND_7: "/images/corn-field-with-silo-background-silo-background.jpg",
  EAR_CORN_CLOSEUP_CORN_PLANT_MAIZE_FIELD_WAITING_HARVEST_8: "/images/ear-corn-closeup-corn-plant-maize-field-waiting-harvest.jpg",
  EFFICIENT_AGRICULTURAL_PRACTICES_UTILIZING_DIGITAL_TABLETS_STREAMLINED_FARMING_PROCESSES_36: "/images/efficient-agricultural-practices-utilizing-digital-tablets-streamlined-farming-processes.jpg",
  EXPORTA_O_E_RASTREABILIDADE_GR_OS_EM_M_OS_9: "/images/Exportação e Rastreabilidade - Grãos em Mãos.png",
  FARMER_IS_WORKING_LUSH_GREEN_FIELD_SUN_IS_SETTING_BACKGROUND_CASTING_WARM_GLOW_SCENE_10: "/images/farmer-is-working-lush-green-field-sun-is-setting-background-casting-warm-glow-scene.jpg",
  FREEPIK_THE_STYLE_IS_CANDID_IMAGE_PHOTOGRAPHY_WITH_NATURAL_94028_32: "/images/freepik__the-style-is-candid-image-photography-with-natural__94028.jpeg",
  GABRIEL_PESCIALLO_23: "/images/gabriel pesciallo.jpeg",
  GENERATED_IMAGE_2026_02_14_11: "/images/generated-image-2026-02-14.png",
  HERD_NELLORE_BOVINE_ANIMALS_HIGH_INTENSIVE_GRASS_SYSTEM_PROJECT_LIVESTOCK_RANCH_12: "/images/herd-nellore-bovine-animals-high-intensive-grass-system-project-livestock-ranch.jpg",
  IMAGENS_AJUSTADAS_6_31: "/images/imagens ajustadas (6).png",
  IMG_1_28: "/images/1.png",
  IMG_628_24: "/images/628.jpg",
  IMG_7_29: "/images/7.png",
  LOGOS_POWERED_BRANCO_26: "/images/logos powered branco.png",
  LOGOS_POWERED_COLOR_27: "/images/logos powered color.png",
  MAIO_JUNHO_OPORTUNIDADE_BOLLS_ABERTOS_1_1: "/images/Maio-Junho Oportunidade - Bolls Abertos (1).png",
  MIDSECTION_MAN_HOLDING_PLANTS_FIELD_14: "/images/midsection-man-holding-plants-field.jpg",
  MILHO_E_PECU_RIA_INTEGRA_O_LAVOURA_15: "/images/Milho e Pecuária - Integração Lavoura.png",
  MODERN_AGRICULTURE_ACTION_POWERFUL_TRACTOR_EFFICIENTLY_TILLING_ROWS_CROPS_DEMONSTRATING_16: "/images/modern-agriculture-action-powerful-tractor-efficiently-tilling-rows-crops-demonstrating.jpg",
  ORGANIC_FARMING_MINIMALIST_IMAGE_CAREERS_AERI_GENERATIVE_AI_17: "/images/organic-farming-minimalist-image-careers-aeri-generative-ai.jpg",
  SELO_CERTIFICA_O_FINAL_V5_25: "/images/selo certificação final v5.png",
  SOYBEAN_FIELD_SUNNY_DAY_AGRICULTURAL_SCENE_18: "/images/soybean-field-sunny-day-agricultural-scene.jpg",
  STALKS_SUGARCANE_PREPARED_PRODUCING_JUICE_19: "/images/stalks-sugarcane-prepared-producing-juice.jpg",
  TECNOLOGIA_EM_MILHO_DRONE_AGR_COLA_20: "/images/Tecnologia em Milho - Drone Agrícola.png",
  TRACTOR_IS_DRIVING_DOWN_FIELD_WITH_SUN_SHINING_IT_21: "/images/tractor-is-driving-down-field-with-sun-shining-it.jpg",
  TRACTOR_IS_PLOWING_FIELD_WITH_SUN_SHINING_HORIZON_22: "/images/tractor-is-plowing-field-with-sun-shining-horizon.jpg",
  TRACTOR_SPRAYING_CROPS_SUNSET_LUSH_GREEN_FIELD_WITH_ROLLING_HILLS_BACKGROUND_41: "/images/tractor-spraying-crops-sunset-lush-green-field-with-rolling-hills-background.jpg",
  TRACTOR_SPRAYING_CROPS_SUNSET_VAST_FIELD_SHOWCASING_AGRICULTURAL_ACTIVITY_VIBRANT_COLORS_SKY_13: "/images/tractor-spraying-crops-sunset-vast-field-showcasing-agricultural-activity-vibrant-colors-sky.jpg",
  TRACTOR_TILLING_SOIL_SUNLIT_FIELD_DAWN_37: "/images/tractor-tilling-soil-sunlit-field-dawn.jpg",
} as const;

export type ImageKey = keyof typeof IMAGES;
